apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: pellefra/auth-service:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: shared-db-storage
              mountPath: /app/databases 
      volumes:
        - name: shared-db-storage
          persistentVolumeClaim:
            claimName: db-pvc 
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
