apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app-frontend
  template:
    metadata:
      labels:
        app: weather-app-frontend
    spec:
      containers:
        - name: weather-app-frontend
          image: pellefra/weather-app-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-frontend
spec:
  selector:
    app: weather-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
