apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
        - name: weather-service
          image: silverland513/weather-service:latest
          ports:
            - containerPort: 5005
          volumeMounts:
            - name: database-storage
              mountPath: /app/databases
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-service
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: LoadBalancer