apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/your/databases

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
        - name: weather-service
          image: pellefra/weather-service:latest
          ports:
            - containerPort: 5005
          volumeMounts:
            - name: weather-db-storage
              mountPath: /app/databases 
      volumes:
        - name: weather-db-storage
          persistentVolumeClaim:
            claimName: db-pvc 

---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-service
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: LoadBalancer
